quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/books20262026
# Casa
#quarkus.datasource.username=postgres
#quarkus.datasource.password=root

# laboratorios
quarkus.datasource.username=postgres
quarkus.datasource.password=labcom,2015


quarkus.flyway.migrate-at-start=false

quarkus.http.port=8080

authors.url.lb=localhost:8070,localhost:8071

# registro estático
#quarkus.stork.authors-api.service-discovery.type=static
#quarkus.stork.authors-api.service-discovery.address-list=${authors.url.lb}
#quarkus.stork.authors-api.load-balancer.type=round-robin

#registro dinámico
quarkus.stork.authors-api.service-discovery.type=consul
quarkus.stork.authors-api.service-discovery.consul-host=${consul.host}
quarkus.stork.authors-api.service-discovery.consul-port=${consul.port}
quarkus.stork.authors-api.service-discovery.application=app-authors
quarkus.stork.authors-api.service-discovery.refresh-period=5s