server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html; # <--- Corregido: Se agregó el ";" que faltaba

    location /app-authors/ {
        proxy_pass http://proxy:8888/app-authors/; # O apunta al contenedor/puerto correcto de tu backend si no usas el proxy de Traefik
    }

    location /app-books/ {
        proxy_pass http://proxy:8888/app-books/;
    }
}