CREATE TABLE authors
(
    "aut-id"   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "aut-name" VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY ("aut-id")
);

CREATE TABLE books
(
    boo_isbn    VARCHAR(255) NOT NULL,
    boo_price   DOUBLE PRECISION,
    boo_title   VARCHAR(255),
    boo_version INTEGER,
    CONSTRAINT pk_books PRIMARY KEY (boo_isbn)
);

CREATE TABLE inventories
(
    inv_bookIsbr VARCHAR(255) NOT NULL,
    inv_solid    INTEGER,
    inv_supplied INTEGER,
    inv_version  INTEGER,
    CONSTRAINT pk_inventories PRIMARY KEY (inv_bookIsbr)
);

ALTER TABLE inventories
    ADD CONSTRAINT FK_INVENTORIES_ON_INV_BOOKISBR FOREIGN KEY (inv_bookIsbr) REFERENCES books (boo_isbn);

CREATE TABLE customer
(
    cus_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cus_email   VARCHAR(255),
    cus_name    VARCHAR(255),
    cus_version INTEGER,
    CONSTRAINT pk_customer PRIMARY KEY (cus_id)
);


CREATE TABLE purchaseorder
(
    pur_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pur_deliveredor TIMESTAMP WITHOUT TIME ZONE,
    pur_placedon    TIMESTAMP WITHOUT TIME ZONE,
    pur_status      INTEGER,
    pur_total       INTEGER,
    pur_customer_id BIGINT,
    CONSTRAINT pk_purchaseorder PRIMARY KEY (pur_id)
);

ALTER TABLE purchaseorder
    ADD CONSTRAINT FK_PURCHASEORDER_ON_PUR_CUSTOMER FOREIGN KEY (pur_customer_id) REFERENCES customer (cus_id);

CREATE TABLE lineitem
(
    lin_idx       INTEGER NOT NULL,
    lin_book_isbr VARCHAR(255),
    lin_quantity  INTEGER,
    lin_order_id  BIGINT  NOT NULL,
    CONSTRAINT pk_lineitem PRIMARY KEY (lin_idx, lin_order_id)
);

ALTER TABLE lineitem
    ADD CONSTRAINT FK_LINEITEM_ON_LIN_ORDER FOREIGN KEY (lin_order_id) REFERENCES purchaseorder (pur_id);


-- Autores
INSERT INTO authors ("aut-name") VALUES ('Gabriel García Márquez'), ('Isabel Allende'), ('Jorge Luis Borges');

-- Libros
INSERT INTO books (boo_isbn, boo_price, boo_title, boo_version)
VALUES ('978-0307474728', 15.99, 'Cien años de soledad', 1),
       ('978-1501117015', 12.50, 'La casa de los espíritus', 1),
       ('978-0307950925', 10.00, 'Ficciones', 1);

-- Inventarios (Corregido el nombre a 'inventories' con N)
INSERT INTO inventories (inv_bookIsbr, inv_solid, inv_supplied, inv_version)
VALUES ('978-0307474728', 5, 20, 1),
       ('978-1501117015', 15, 30, 1),
       ('978-0307950925', 2, 10, 1);

-- Clientes
INSERT INTO customer (cus_email, cus_name, cus_version)
VALUES ('steven.g@example.com', 'Steven Guerrero', 1),
       ('maria.l@example.com', 'Maria Lopez', 1),
       ('juan.p@example.com', 'Juan Perez', 1);

-- Órdenes
INSERT INTO purchaseorder (pur_placedon, pur_status, pur_total, pur_customer_id, pur_deliveredor)
VALUES (CURRENT_TIMESTAMP, 1, 45, 1, NULL),
       (CURRENT_TIMESTAMP, 1, 25, 2, NULL),
       (CURRENT_TIMESTAMP, 2, 10, 3, CURRENT_TIMESTAMP);

-- Detalles de orden
INSERT INTO lineitem (lin_order_id, lin_idx, lin_book_isbr, lin_quantity)
VALUES (1, 1, '978-0307474728', 2),
       (1, 2, '978-1501117015', 1),
       (2, 1, '978-0307950925', 1);