CREATE TABLE authors
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

CREATE TABLE books_authors
(
    books_isbn VARCHAR(255) NOT NULL,
    authors_id INTEGER      NOT NULL,
    CONSTRAINT pk_books_authors PRIMARY KEY (books_isbn, authors_id)
);

ALTER TABLE books_authors
    ADD CONSTRAINT FK_BOOKS_AUTHORS_ON_AUTHORS FOREIGN KEY (authors_id) REFERENCES authors (id);

insert into authors (name) values ('J.K. Rowling');
insert into authors (name) values ('George R.R. Martin');
insert into authors (name) values ('J.R.R. Tolkien');

insert into books_authors (books_isbn, authors_id) values ('978-0544003415', 1);
insert into books_authors (books_isbn, authors_id) values ('978-0553103540', 2);
insert into books_authors (books_isbn, authors_id) values ('978-0544003415', 3);
